import { PrismaClient, StudentSex, StudentStatus } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
    const students = [
    {
      studentId: 'SV001',
      name: 'Nguyễn Văn An',
      dob: new Date('2000-01-15'),
      sex: StudentSex.MALE,
      faculty: 'Khoa Luật',
      cohort: 2020,
      program: 'Cử nhân Luật',
      address: '123 Trần Hưng Đạo, Hà Nội',
      phone: '0912345678',
      email: 'an.nguyen@edu.vn',
      status: StudentStatus.ACTIVE,
    },
    {
      studentId: 'SV002',
      name: 'Trần Thị Bình',
      dob: new Date('2001-03-22'),
      sex: StudentSex.FEMALE,
      faculty: 'Khoa Tiếng Anh thương mại',
      cohort: 2021,
      program: 'Cử nhân Tiếng Anh thương mại',
      address: '456 Lê Lợi, TP. Hồ Chí Minh',
      phone: '0987654321',
      email: 'binh.tran@edu.vn',
      status: StudentStatus.ACTIVE,
    },
    {
      studentId: 'SV003',
      name: 'Lê Minh Châu',
      dob: new Date('1999-07-10'),
      sex: StudentSex.MALE,
      faculty: 'Khoa Tiếng Nhật',
      cohort: 2019,
      program: 'Cử nhân Tiếng Nhật',
      address: '789 Nguyễn Trãi, Đà Nẵng',
      phone: '0935123456',
      email: 'chau.le@edu.vn',
      status: StudentStatus.GRADUATED,
    },
    {
      studentId: 'SV004',
      name: 'Phạm Thị Dung',
      dob: new Date('2002-05-18'),
      sex: StudentSex.FEMALE,
      faculty: 'Khoa Tiếng Pháp',
      cohort: 2022,
      program: 'Cử nhân Tiếng Pháp',
      address: null,
      phone: '0901234567',
      email: 'dung.pham@edu.vn',
      status: StudentStatus.ACTIVE,
    },
    {
      studentId: 'SV005',
      name: 'Hoàng Văn Nam',
      dob: new Date('2000-11-30'),
      sex: StudentSex.MALE,
      faculty: 'Khoa Luật',
      cohort: 2020,
      program: 'Cử nhân Luật',
      address: '101 Lý Thường Kiệt, Hà Nội',
      phone: '0945678901',
      email: 'nam.hoang@edu.vn',
      status: StudentStatus.SUSPENDED,
    },
    {
      studentId: 'SV006',
      name: 'Vũ Thị Hoa',
      dob: new Date('2001-09-05'),
      sex: StudentSex.FEMALE,
      faculty: 'Khoa Tiếng Anh thương mại',
      cohort: 2021,
      program: 'Cử nhân Tiếng Anh thương mại',
      address: '202 Hoàng Diệu, Huế',
      phone: '0923456789',
      email: 'hoa.vu@edu.vn',
      status: StudentStatus.ACTIVE,
    },
    {
      studentId: 'SV007',
      name: 'Đỗ Minh Quân',
      dob: new Date('1998-12-12'),
      sex: StudentSex.MALE,
      faculty: 'Khoa Tiếng Nhật',
      cohort: 2018,
      program: 'Cử nhân Tiếng Nhật',
      address: '303 Bà Triệu, Hà Nội',
      phone: null,
      email: 'quan.do@edu.vn',
      status: StudentStatus.GRADUATED,
    },
    {
      studentId: 'SV008',
      name: 'Nguyễn Thị Lan',
      dob: new Date('2002-02-25'),
      sex: StudentSex.FEMALE,
      faculty: 'Khoa Tiếng Pháp',
      cohort: 2022,
      program: 'Cử nhân Tiếng Pháp',
      address: '404 Hai Bà Trưng, TP. Hồ Chí Minh',
      phone: '0971234567',
      email: null,
      status: StudentStatus.ACTIVE,
    },
    {
      studentId: 'SV009',
      name: 'Trần Văn Khải',
      dob: new Date('2000-04-08'),
      sex: StudentSex.MALE,
      faculty: 'Khoa Luật',
      cohort: 2020,
      program: 'Cử nhân Luật',
      address: '505 Nguyễn Huệ, Đà Nẵng',
      phone: '0967891234',
      email: 'khai.tran@edu.vn',
      status: StudentStatus.WITHDRAWN,
    },
    {
      studentId: 'SV010',
      name: 'Lê Thị Mai',
      dob: new Date('2001-06-17'),
      sex: StudentSex.FEMALE,
      faculty: 'Khoa Tiếng Anh thương mại',
      cohort: 2021,
      program: 'Cử nhân Tiếng Anh thương mại',
      address: null,
      phone: '0956789012',
      email: 'mai.le@edu.vn',
      status: StudentStatus.ACTIVE,
    },
    {
      studentId: 'SV011',
      name: 'Phạm Văn Long',
      dob: new Date('1999-08-20'),
      sex: StudentSex.MALE,
      faculty: 'Khoa Tiếng Nhật',
      cohort: 2019,
      program: 'Cử nhân Tiếng Nhật',
      address: '606 Trần Phú, Cần Thơ',
      phone: '0916782345',
      email: 'long.pham@edu.vn',
      status: StudentStatus.GRADUATED,
    },
    {
      studentId: 'SV012',
      name: 'Hoàng Thị Ngọc',
      dob: new Date('2002-10-03'),
      sex: StudentSex.FEMALE,
      faculty: 'Khoa Tiếng Pháp',
      cohort: 2022,
      program: 'Cử nhân Tiếng Pháp',
      address: '707 Lê Lai, Hà Nội',
      phone: '0937894561',
      email: 'ngoc.hoang@edu.vn',
      status: StudentStatus.ACTIVE,
    },
    {
      studentId: 'SV013',
      name: 'Vũ Minh Tuấn',
      dob: new Date('2000-03-14'),
      sex: StudentSex.MALE,
      faculty: 'Khoa Luật',
      cohort: 2020,
      program: 'Cử nhân Luật',
      address: '808 Võ Văn Kiệt, TP. Hồ Chí Minh',
      phone: null,
      email: 'tuan.vu@edu.vn',
      status: StudentStatus.SUSPENDED,
    },
    {
      studentId: 'SV014',
      name: 'Nguyễn Thị Thủy',
      dob:  new Date('2001-01-27'),
      sex: StudentSex.FEMALE,
      faculty: 'Khoa Tiếng Anh thương mại',
      cohort: 2021,
      program: 'Cử nhân Tiếng Anh thương mại',
      address: '909 Nguyễn Văn Cừ, Hà Nội',
      phone: '0941237890',
      email: 'thuy.nguyen@edu.vn',
      status: StudentStatus.ACTIVE,
    },
    {
      studentId: 'SV015',
      name: 'Trần Văn Phúc',
      dob: new Date('1999-05-09'),
      sex: StudentSex.MALE,
      faculty: 'Khoa Tiếng Nhật',
      cohort: 2019,
      program: 'Cử nhân Tiếng Nhật',
      address: '1010 Lý Nam Đế, Huế',
      phone: '0926781234',
      email: 'phuc.tran@edu.vn',
      status: StudentStatus.WITHDRAWN,
    },
  ];
  for (const student of students) {
    await prisma.student.create({
      data: student
    });
  }
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });